#Dependencies
highlighter: rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Eren Yıldırım
tagline:             Tech Enthusiast
url:                 http://erenyildirim.com
paginate:            1
baseurl:             "http://erenyildirim.com"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Eren Yıldırım
  url:               https://twitter.com/ernyldrm
  email:             mail@erenyildirim.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/poole/poole

# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

gems:
  - jekyll-redirect-from
